baseURL = '/'
languageCode = 'en-us'
title = 'the maus haus'
theme = 'pulp'

[params]
    author = "the maus haus"
    avatar = "avatar.jpg"
    avatarDescription = "the maus haus"
    favicon = "favicon.ico"
    # description = "the maus haus"
    publicationYear = "2023"
